version: "3"

services:
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "4000:80"
  kong:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: kong docker-start
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/plugin/config/kong.yml
      - KONG_PLUGINS=bundled,jwt-claims-headers
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_LOG_LEVEL=debug
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
    volumes:
      - .:/plugin
